# Generated by Django 3.2.20 on 2023-09-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_todoitem_check_execute1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='check_execute1',
        ),
    ]
