# Generated by Django 3.2.20 on 2023-09-06 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_remove_todoitem_check_execute1'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
